// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/documents": {
            "get": {
                "description": "Obtiene la lista completa de documentos fiscales",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "documents"
                ],
                "summary": "Listar todos los documentos",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Document"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    }
                }
            },
            "post": {
                "description": "Crea un nuevo documento fiscal con sus items y validación",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "documents"
                ],
                "summary": "Crear nuevo documento",
                "parameters": [
                    {
                        "description": "Datos del documento",
                        "name": "document",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Document"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Document"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    }
                }
            }
        },
        "/documents/verify": {
            "post": {
                "description": "Verifica la validez de la firma digital de un documento",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "documents"
                ],
                "summary": "Verificar firma de documento",
                "parameters": [
                    {
                        "description": "Documento y firma",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.VerifyDocumentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.VerifyDocumentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    }
                }
            }
        },
        "/documents/{id}": {
            "get": {
                "description": "Obtiene un documento específico mediante su ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "documents"
                ],
                "summary": "Obtener documento por ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del documento",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Document"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    }
                }
            },
            "put": {
                "description": "Actualiza los datos de un documento existente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "documents"
                ],
                "summary": "Actualizar documento",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del documento",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos actualizados",
                        "name": "document",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Document"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Document"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Elimina permanentemente un documento del sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "documents"
                ],
                "summary": "Eliminar documento",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del documento",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Document": {
            "type": "object",
            "properties": {
                "fechaEmision": {
                    "type": "string",
                    "example": "2026-02-12T10:00:00Z"
                },
                "idDocumento": {
                    "type": "string",
                    "example": "DOC-001"
                },
                "igvTotal": {
                    "type": "number",
                    "example": 180
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Item"
                    }
                },
                "montoTotal": {
                    "type": "number",
                    "example": 1180
                },
                "montoTotalSinImpuestos": {
                    "type": "number",
                    "example": 1000
                },
                "rucEmisor": {
                    "type": "string",
                    "example": "20123456789"
                },
                "rucReceptor": {
                    "type": "string",
                    "example": "20987654321"
                },
                "uuid": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "validacion": {
                    "$ref": "#/definitions/domain.Validacion"
                }
            }
        },
        "domain.Item": {
            "type": "object",
            "properties": {
                "cantidad": {
                    "type": "integer",
                    "example": 5
                },
                "descripcion": {
                    "type": "string",
                    "example": "Producto A"
                },
                "igvTotal": {
                    "type": "number",
                    "example": 90
                },
                "precioTotal": {
                    "type": "number",
                    "example": 500
                },
                "precioUnitario": {
                    "type": "number",
                    "example": 100
                }
            }
        },
        "domain.Validacion": {
            "type": "object",
            "properties": {
                "estado": {
                    "type": "string",
                    "example": "VALIDO"
                },
                "fechaValidacion": {
                    "type": "string",
                    "example": "2026-02-12T10:00:00Z"
                },
                "firma": {
                    "type": "string",
                    "example": "abc123def456"
                }
            }
        },
        "errors.AppError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Bad Request"
                },
                "message": {
                    "type": "string",
                    "example": "Error en la solicitud"
                },
                "status": {
                    "type": "integer",
                    "example": 400
                }
            }
        },
        "handler.VerifyDocumentRequest": {
            "type": "object",
            "required": [
                "documento",
                "firma"
            ],
            "properties": {
                "documento": {
                    "$ref": "#/definitions/domain.Document"
                },
                "firma": {
                    "type": "string"
                }
            }
        },
        "handler.VerifyDocumentResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "valid": {
                    "type": "boolean"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Operaciones relacionadas con documentos fiscales",
            "name": "documents"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:5001",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "MS1 Documents API",
	Description:      "API para gestión de documentos fiscales con validación y firma digital\nEste microservicio permite crear, consultar, actualizar y eliminar documentos.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
